version: "3.3"

services:
  nginx:
    restart: always
    container_name: nginx-service
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    links:
      - php
  php:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - 9000


